# Generated by Django 4.2.6 on 2023-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_management', '0002_alter_book_authors_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
